import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const TOOL_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(TOOL_DIR, '../..');
const PACKAGE_JSON_PATH = path.join(TOOL_DIR, 'node_modules/@mozilla/readability/package.json');
const OUTPUT_PATH = path.join(
  REPO_ROOT,
  'AiraBrowser/entry/src/main/ets/features/reader/ReaderReadabilityRuntimeSource.ets'
);
const EXPECTED_VERSION = '0.6.0';

const packageJson = JSON.parse(await readFile(PACKAGE_JSON_PATH, 'utf8'));
if (packageJson.version !== EXPECTED_VERSION) {
  throw new Error(`Expected @mozilla/readability ${EXPECTED_VERSION}, received ${packageJson.version}`);
}

const bundled = await build({
  stdin: {
    contents: `export { Readability } from '@mozilla/readability';`,
    resolveDir: TOOL_DIR,
    sourcefile: 'aira-reader-readability-entry.js',
    loader: 'js'
  },
  bundle: true,
  format: 'iife',
  globalName: 'AiraReaderReadability',
  platform: 'browser',
  minify: true,
  legalComments: 'none',
  write: false,
  logLevel: 'silent'
});

const runtimeSource = bundled.outputFiles[0].text.trim();
const runtimeSha256 = createHash('sha256').update(runtimeSource).digest('hex');
const generated = `// Generated by tools/reader-extraction-spike/generate-runtime.mjs. Do not edit manually.\n` +
  `// Mozilla Readability ${EXPECTED_VERSION}, Apache-2.0. See third_party/mozilla-readability/README.md.\n` +
  `export const MOZILLA_READABILITY_VERSION: string = ${JSON.stringify(EXPECTED_VERSION)};\n` +
  `export const MOZILLA_READABILITY_RUNTIME_SHA256: string = ${JSON.stringify(runtimeSha256)};\n` +
  `export const MOZILLA_READABILITY_RUNTIME_SOURCE: string = ${JSON.stringify(runtimeSource)};\n`;

await writeFile(OUTPUT_PATH, generated, 'utf8');
console.log(JSON.stringify({
  output: path.relative(REPO_ROOT, OUTPUT_PATH),
  version: EXPECTED_VERSION,
  bytes: Buffer.byteLength(runtimeSource),
  sha256: runtimeSha256
}, null, 2));
