export const HOME_PAGE_PRESENTATION_SHOW_FAVORITES_TITLE_KEY: string =
  'homePagePresentationShowFavoritesTitle';
export const HOME_PAGE_PRESENTATION_SHOW_SHORTCUT_NAMES_KEY: string =
  'homePagePresentationShowShortcutNames';
export const HOME_PAGE_PRESENTATION_SHOW_RECENTLY_CLOSED_TITLE_KEY: string =
  'homePagePresentationShowRecentlyClosedTitle';
export const HOME_PAGE_PRESENTATION_SHOW_SETTINGS_BUTTON_KEY: string =
  'homePagePresentationShowSettingsButton';
