export type AiraFeatureKey =
  'cloud_sync' |
  'webdav_sync' |
  'bookmark_auto_sync' |
  'phone_page_push' |
  'cross_device_tabs' |
  'cloud_translation' |
  'offline_page_save' |
  'offline_page_export' |
  'advanced_download' |
  'manual_element_hide' |
  'userscript_install' |
  'userscript_advanced_api' |
  'webapp_install' |
  'webapp_advanced_management' |
  'native_video_takeover' |
  'native_video_background_playback' |
  'site_customization' |
  'labs_feature' |
  'bing_wallpaper_auto_refresh';

export const AIRA_FEATURE_OFFLINE_PAGE_SAVE: AiraFeatureKey = 'offline_page_save';
export const AIRA_FEATURE_CLOUD_SYNC: AiraFeatureKey = 'cloud_sync';
export const AIRA_FEATURE_WEBDAV_SYNC: AiraFeatureKey = 'webdav_sync';
export const AIRA_FEATURE_BOOKMARK_AUTO_SYNC: AiraFeatureKey = 'bookmark_auto_sync';
export const AIRA_FEATURE_PHONE_PAGE_PUSH: AiraFeatureKey = 'phone_page_push';
export const AIRA_FEATURE_CROSS_DEVICE_TABS: AiraFeatureKey = 'cross_device_tabs';
export const AIRA_FEATURE_CLOUD_TRANSLATION: AiraFeatureKey = 'cloud_translation';
export const AIRA_FEATURE_USERSCRIPT_INSTALL: AiraFeatureKey = 'userscript_install';
export const AIRA_FEATURE_MANUAL_ELEMENT_HIDE: AiraFeatureKey = 'manual_element_hide';
export const AIRA_FEATURE_WEBAPP_INSTALL: AiraFeatureKey = 'webapp_install';
export const AIRA_FEATURE_NATIVE_VIDEO_BACKGROUND_PLAYBACK: AiraFeatureKey = 'native_video_background_playback';
export const AIRA_FEATURE_LABS_FEATURE: AiraFeatureKey = 'labs_feature';
